### ISSUE TITLE
Curating keywords

### ISSUE THREAD

**Issue by dpancic** [SSHOC/marketplace-curation#1]
In GitLab by @KlausIllmayer on Apr 4, 2022, 16:50

The keywords-vocabulary is used to add all kinds of concepts. It is the only open vocabulary. New created concepts are marked as candidate concepts. It is necessary to go through the list of candidate concepts and either accept, reject or map them to a better fitting concept.

The workflow for the keywords curation looks like this:
* we do have a gSpreadsheet with two sheets: a list of mappings and a list of rejections
* there is a notebook that reads from this gSpreadsheet and regularly is run
  * the notebook rejects the keyword concepts from the list
  * it maps the ones from the list by applying the mapped concept to the items that use the keyword concept, then deletes the keyword concept from the items and in the end rejects the keyword concept
* this implies that accepting keywords will be done by administrators
* in the end, there should be no candidate concepts after running the scrip9t
  * if this is the case, an skos-export will be done, which will be then distributed to the vocabulary-commons-server (vocabs.sshopencloud.eu)
* as long as candidate concepts are there, it is necessary to update the gSpreadsheet or to accept remaining keywords

The gSpreadsheet is public viewable but only editable if you have permission (contact @KlausIllmayer): https://docs.google.com/spreadsheets/d/1-Oh9_SxIhfMAT6KNJrMf4LetCpy5s1fHZEyTL__TUVA/edit?usp=sharing

**Comment by laureD19** [comment]
regarding [notebook 5.2](https://github.com/SSHOC/marketplace-curation/blob/dev/5.2CurationKeywords-Duplicates.ipynb) and the curation of duplicated values within the same property or across several properties and after looking at the results with Martin @aureon249, here are a few suggestions and questions to curate the items involved. But as noticed by Klaus in a [comment above](https://github.com/SSHOC/marketplace-curation/issues/1#issuecomment-1352923175), issues creating these cases should be tackled by the ingest pipeline in the future. 

Here are three suggestions to clean the ~1000 items involved:
- if two (or more) identical concepts are found within the same property, only one occurrence should be kept and the rest deleted. 
- if two identical concepts across different properties and involving keyword are found - example: `activity: mapping, keyword: mapping`  or `keyword: cidoc-crm, standard: cidoc-crm` - we should follow [notebook 5.1 workflow](https://github.com/SSHOC/marketplace-curation/blob/dev/5.1CurationKeywords.ipynb) to clean the keyword vocabulary and include the mapping between vocabularies in the [keyword mappings/rejection Gsheet](https://docs.google.com/spreadsheets/d/1-Oh9_SxIhfMAT6KNJrMf4LetCpy5s1fHZEyTL__TUVA/edit#gid=0) . @KlausIllmayer do you think it is ok to proceed like that, even if we are not dealing with candidate concepts here?  
- if two identical concepts across different properties (not involving keyword) are found, a further investigation should be conducted. We didn't see any cases like that, but it might be we missed something.


(two comments to pass on the ingest team:
- only one occurrence of a value per property should be allowed
- behavior of the concept-search and exact match between values at source and values ingested is unclear (Ex: “data linking” at source, mapped to “Linked-open-data” in MP or “data protecting” at source mapped to “protection of personal data” in MP))


@cesareconcordia does it sound doable to implement these suggestions?

notify also @vronk @kreetrapper

**Comment by cesareconcordia** [comment]
In the spreadsheet there are duplicated values in ‘Keyword to map’ column (ex rows 167 and 168),  if i understand correctly,  this means that the procedure in these cases needs to replace the wrong value and also  to create a new value, @KlausIllmayer could you confirm this? 
If yes, could you give me information on how a new keyword can be created?

**Comment by KlausIllmayer** [comment]
@cesareconcordia It is not necessary to create a new keyword. It means that a keyword should be mapped to two or more existing concepts in other vocabularies. In the case of row 167 and 168: both point to the existing keyword `Information Retrieval > Analysis-Content Analysis` which should be mapped to the property `activity` and the code `informationRetrieval` (= map to `https://vocabs.dariah.eu/tadirah/informationRetrieval`, row 167) **as well as** the property `activity` and the code `contentAnalysis` (= map to `https://vocabs.dariah.eu/tadirah/contentAnalysis`, row 168). So every item having the keyword `Information Retrieval > Analysis-Content Analysis` should in the end have the two additional activity codes 'informationRetrieval'  and 'contentAnalysis'. Afterwards the keyword `Information Retrieval > Analysis-Content Analysis` can be deleted. So there is no new keyword in use. Only more than one mapping (and the need to delete already mapped keywords after processing the full spreadsheet).

**Comment by KlausIllmayer** [comment]
To give an example how it would look like with a replace in the JSON:

Lets take the example from row 167 and 168. The keyword `Information Retrieval > Analysis-Content Analysis` is only used by the item https://marketplace-api.sshopencloud.eu/api/tools-services/yLajJg

Find there the keyword that is mapped:
```
    {
      "type": {
        "code": "keyword",
        "label": "Keyword",
        "type": "concept",
        "groupName": "Categorisation",
        "hidden": false,
        "ord": 18,
        "allowedVocabularies": [
          {
            "code": "sshoc-keyword",
            "scheme": "https://vocabs.dariah.eu/sshoc-keyword/Schema",
            "namespace": "https://vocabs.dariah.eu/sshoc-keyword/",
            "label": "Keywords from SSHOC MP",
            "closed": false
          }
        ]
      },
      "concept": {
        "code": "Information+Retrieval+%3E+Analysis-Content+Analysis",
        "vocabulary": {
          "code": "sshoc-keyword",
          "scheme": "https://vocabs.dariah.eu/sshoc-keyword/Schema",
          "namespace": "https://vocabs.dariah.eu/sshoc-keyword/",
          "label": "Keywords from SSHOC MP",
          "closed": false
        },
        "label": "Information Retrieval > Analysis-Content Analysis",
        "notation": "",
        "uri": "https://vocabs.dariah.eu/sshoc-keyword/Information+Retrieval+%3E+Analysis-Content+Analysis",
        "candidate": true
      }
    },
```
This should be replaced with the two dynamic properties "activity => informationRetrieval" and "activity => contentAnalysis", which would look in JSON like this:
```
    {
      "type": {
        "code": "activity"
      },
      "concept": {
        "code": "informationRetrieval",
        "vocabulary": {
          "code": "tadirah2"
        },
        "uri": "https://vocabs.dariah.eu/tadirah/informationRetrieval"
      }
    },
    {
      "type": {
        "code": "activity"
      },
      "concept": {
        "code": "contentAnalysis",
        "vocabulary": {
          "code": "tadirah2"
        },
        "uri": "https://vocabs.dariah.eu/tadirah/contentAnalysis"
      }
    },
```

**Comment by cesareconcordia** [comment]
Hi, the Notebook 5.1 (dev branch) implements the replacement of a property with one or more dynamic properties, I've tested it on  the 'stage' dataset (for a limited number of keywords) and it seems working, let me know if you test it and have problems. 
I'm currently starting to work to the rejection of keywords, the idea is to implement a simple function that: a) searches for items that has one or more keywords listed in the 'rejecting' sheet, b) removes the properties, c) write back the item data. I'm not sure if this could cause inconsistencies, @KlausIllmayer what do you think?

**Comment by KlausIllmayer** [comment]
> I'm currently starting to work to the rejection of keywords, the idea is to implement a simple function that: a) searches for items that has one or more keywords listed in the 'rejecting' sheet, b) removes the properties, c) write back the item data. I'm not sure if this could cause inconsistencies, @KlausIllmayer what do you think?

@cesareconcordia I think this is the right way to go and I don't think that it will create inconsistencies. We only have the issue, that this will not delete the concept from the vocabulary itself. For this, we need a dedicated call to the API endpoint `DELETE /api/vocabularies/{vocabulary-code}/concepts/{code}`. But this is also true for the mapping that we already do, as mapping to a different concept should also result in deleting the original concept. To solve this, we need another routine that does the cleanup of the sshoc-keyword-vocabulary concepts:

1.  Go through all concepts of the vocabulary `keywords` => `GET /api/vocabularies/sshoc-keyword` (this is a case-sensitive list)
2. Look, if the keyword is not connected to any item => `GET /api/item-search` and search in the result of this call if in the object `"facets": {"keyword": ...}` the concept shows up (beware, case-sensitive)
3. If the concept is not there (it shows only concepts that are connected to one or more items) this means, we can delete it with calling `DELETE /api/vocabularies/sshoc-keyword/concepts/{code}` (the code needs to come from the first call)

@cesareconcordia Would it possible, to create such a routine?
@laureD19 Do you agree that we like to delete all keywords, that are not connected to an item?

**Comment by cesareconcordia** [comment]
> 1. Go through all concepts of the vocabulary `keywords` => `GET /api/vocabularies/sshoc-keyword` (this is a case-sensitive list)
> 2. Look, if the keyword is not connected to any item => `GET /api/item-search` and search in the result of this call if in the object `"facets": {"keyword": ...}` the concept shows up (beware, case-sensitive)
> 3. If the concept is not there (it shows only concepts that are connected to one or more items) this means, we can delete it with calling `DELETE /api/vocabularies/sshoc-keyword/concepts/{code}` (the code needs to come from the first call)

This can be implemented, however so far the 'DELETE' method has no yet been used. Next week I'll do some tests.

**Comment by KlausIllmayer** [comment]
Regarding the Keyword-Mappings-document:

We need some further rules there, otherwise we may run into troubles:

To make things easier, we decided that the curation script for mapping/rejecting works in a case-insensitive way. If there is the concept "analysis" to map, the script will also map "Analysis", "AnAlYsIs", etc. Thus, we don't need to add every possible combination of letter-cases in a word to the list. This makes it easier for creating this list but has some side effects:

* We should not have the same word with different lower- and uppercase characters in the list, as the script will apply for every entry the mapping algorithm. Therefore we should check that such duplicates are not in the list. The easiest way is to activate the sort filter on the "keyword to map"-field and check if there are same case-insensitive concepts. If so, delete until there is only one left (as it is case-insensitive, it makes no difference which one is left). This should be also done for every new entry: check if a case-insensitive mapping/rejection already exists for a concept. But be aware, there are sometimes reasons, why a concept has duplicates in the list, e.g. because it is mapped to two or more other concepts. Rule of thumb: if case-insensitive-duplicates "map to" the same concept, then delete from the list all of them expect one.

* There is also an issue with the mapping of concepts within the sshoc-keyword-vocabulary, e.g. I see the mapping "bookmark" that maps to https://vocabs.dariah.eu/sshoc-keyword/bookmarking. The issue here is, that the vocabularies in the marketplace are case-sensitive. This means, that there is difference between the concepts "Bookmarking" and "bookmarking" (it will also show up in the url: https://vocabs.dariah.eu/sshoc-keyword/bookmarking vs. https://vocabs.dariah.eu/sshoc-keyword/Bookmarking). So this is on the one hand a reminder that we need to be aware about this and that we need to agree if we like to have verbs starting with lower-case and (proper) nouns with upper-case. On the other hand it rises the issue how we handle clean-up of case-sensitive duplicates in the sshoc-keyword. As the script is case-insensitive we currently handle this case only if you aware about different ways of writing one concept, e.g. `Bookmarking` and `bookmarking` and explicitly adding this into the mapping list:` "Bookmarking" => https://vocabs.dariah.eu/sshoc-keyword/bookmarking`. But this would lead to a pollution of the history of "bookmarking", as the script will not only handle "Bookmarking" every time but also "bookmarking" (remember, the script is case-insensitive), so that in every run of the script the items with "bookmarking" are also again mapped to "bookmarking". Writing down this long paragraph, I think the best solution could be to have a dedicated script against case-sensitive-duplicates but we don't have a chance to define, which of the duplicates the script should prefer, if we have a verb=lower-case-start and noun=upper-case-start.

Okay, this went far too long, therefore asking @laureD19 if all of this makes sense and what you think about the mappings within the sshoc-keyword-vocabulary and the issue with the case-sensitive duplicates?

* Another remark just for me: after we do a new upload of the sshoc-keyword with the new domain (not vocabs.dariah.eu instead vocabs.sshopencloud.eu) it is also necessary to change the mappings/rejections.

**Comment by KlausIllmayer** [comment]
Another issue with the mapping table: we need to be very careful with the mappings from sshoc-keyword to sshoc-keyword. It will be necessary to check if the map to sshoc-keyword is not also mapped to something else, e.g. there is a mapping `"excel" => "https://vocabs.dariah.eu/sshoc-keyword/ms excel"` but we also have the mapping `"ms excel" => "https://vocabs.sshopencloud.eu/vocabularies/media-type/applicationslashvnd.ms-excel"`. This could raise a problem depending on the order the script is processing the table: if first "ms excel" is processed, then it maps everything to the media-type, but when afterwards "excel" has its turn, it will create new "ms excel" items, which we don't like to have. Therefore the "excel" should be only mapped to `"https://vocabs.sshopencloud.eu/vocabularies/media-type/applicationslashvnd.ms-excel"` - just a reminder (and maybe we should start a dedicated table in the spreadsheet with the rules to follow).

Including @laureD19

**Comment by KlausIllmayer** [comment]
Including @aureon249 to the discussion

**Comment by KlausIllmayer** [comment]
>     2. Look, if the keyword is not connected to any item => `GET /api/item-search` and search in the result of this call if in the object `"facets": {"keyword": ...}` the concept shows up (beware, case-sensitive)

regarding the deletion of keywords: we found out that step 2 of the workflow will not work, because `GET /api/item-search` delivers back in the keyword-facets the label and not the code (and the code differs from label because it will introduce a camelCase and will replace special characters like space with the plus-symbol). this leads to problems when it comes to identify keywords from this list

instead it is necessary to harvest the used keywords by going through the complete list of items in the notebook.

**Comment by KlausIllmayer** [comment]
There is a new workflow in place, which already looks very promising:

1. The script looks for all the keywords that are not in use, going through the full list of published items
2. The crafted list is then used to run `DELETE /api/vocabularies/sshoc-keyword/concepts/{code}` against every keyword. This will delete all the keywords that were never applied to an item. Doing this the first time will delete some keywords, afterwards we expect that such orphaned keywords do not show up that often (but they could: users can start to create an item, propose inside the edit form a new keyword but never save the item - in such cases, a keyword will be orphaned)
3. For the remaining keywords of the list we run now a `DELETE /api/vocabularies/sshoc-keyword/concepts/{code}?force=true` which will also delete keywords, that were once applied to an item (but there are some issues here, which we need to discuss, see below)
4. In theory, there should be now no keyword left, which is not applied to at least one active item. But we do get still some keywords when now running again step 1. We suspect that this is due a pagination error of the keyword list coming from backend, see https://github.com/SSHOC/sshoc-marketplace-backend/issues/397 - as long as we don't find a solution for this, we take the usual workaround, to run the steps 1, 2 and 3 as long as there is no keyword left when running again step 1.

If I missed something @cesareconcordia can you expand the workflow description?

**Comment by KlausIllmayer** [comment]
Coming to the issue we have with the `force=true`-parameter when deleting keywords. The current workflow can't access items that are drafted or that are suggested. The only visible items are the ones that are approved and active. This means that if a user created a draft with a new keyword that is still in state draft (or in state suggested) when running the workflow, we will not be aware about it and it will look like that the keyword is not in use. Unfortunately, the DELETE with force=true does not take this in account. It will delete such keywords.
Which could be seen as false positives and could lead to irritations for users that suddenly miss their keyword. On the other hand, if someone drafted an item and forget about it, having a strange new keyword, this keyword will stay as long as either the draft is deleted externally or the user remembers the draft version. There is no perfect solution, but we should decide about our policy here. If we like to stay with keywords that are only applied to drafted and/or suggested and/or ingested items (I guess the same is true for new keywords of ingested items, which indeed would be not good) there are two options:
* Don't run the keyword curation script as long as there are suggested and ingested items to approve (this will not solve the issue with the draft items, but maybe this is okay)
* Update the DELETE concept of vocabulary with draft=true endpoint of the API in the endpoint and introduce the rules that we decide about.

Opinions @laureD19 @kreetrapper @cesareconcordia ?

**Comment by laureD19** [comment]
issue closed - replaced by https://github.com/SSHOC/marketplace-curation/issues/13
